//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.22 at 10:30:25 ÏÂÎç CST 
//


package org.net9.arnetpie.data;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.net9.arnetpie.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.net9.arnetpie.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mail }
     * 
     */
    public Mail createMail() {
        return new Mail();
    }

    /**
     * Create an instance of {@link Groupprofile }
     * 
     */
    public Groupprofile createGroupprofile() {
        return new Groupprofile();
    }

    /**
     * Create an instance of {@link Notifications }
     * 
     */
    public Notifications createNotifications() {
        return new Notifications();
    }

    /**
     * Create an instance of {@link Pages.Pdf }
     * 
     */
    public Pages.Pdf createPagesPdf() {
        return new Pages.Pdf();
    }

    /**
     * Create an instance of {@link Pages.WikiPage }
     * 
     */
    public Pages.WikiPage createPagesWikiPage() {
        return new Pages.WikiPage();
    }

    /**
     * Create an instance of {@link Pages }
     * 
     */
    public Pages createPages() {
        return new Pages();
    }

    /**
     * Create an instance of {@link Notifications.Notification }
     * 
     */
    public Notifications.Notification createNotificationsNotification() {
        return new Notifications.Notification();
    }

    /**
     * Create an instance of {@link Userprofile }
     * 
     */
    public Userprofile createUserprofile() {
        return new Userprofile();
    }

}
