//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.22 at 10:30:25 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://arnetpie.net9.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.net9.arnetpie.data;
